export interface HerbalRemedyDetailed {
  id: string
  name: string
  koreanName?: string
  sanskritName?: string
  system: "korean" | "ayurvedic" | "both"
  category: string
  energetics: {
    temperature: "cold" | "cool" | "neutral" | "warm" | "hot"
    taste: string[]
    element?: string
    dosha?: "vata" | "pitta" | "kapha" | "tridoshic"
  }
  benefits: string[]
  symptoms: string[]
  activeCompounds: string[]
  dosage: {
    tea: string
    decoction: string
    powder: string
    tincture: string
  }
  contraindications: string[]
  interactions: string[]
  sideEffects: string[]
  researchStudies: { title: string; year: number }[]
  season: "spring" | "summer" | "autumn" | "winter" | "year-round"
  traditionalUse: string
  preparation: string
  storageInstructions: string
  priceRange: string
  availability: "common" | "moderate" | "rare"
  scientificName: string
  partUsed: string
}

export const koreanHerbs: HerbalRemedyDetailed[] = [
  {
    id: "korean-ginseng-001",
    name: "Korean Ginseng",
    koreanName: "홍삼 (Hong Sam)",
    system: "korean",
    category: "Tonic & Vitality",
    energetics: {
      temperature: "warm",
      taste: ["sweet", "slightly bitter"],
      element: "earth",
    },
    benefits: [
      "Boosts energy and stamina",
      "Enhances cognitive function",
      "Supports immune system",
      "Improves circulation",
      "Reduces stress and fatigue",
      "Enhances sexual function",
    ],
    symptoms: ["fatigue", "low energy", "poor concentration", "stress", "weakness"],
    activeCompounds: ["ginsenosides", "polysaccharides", "peptidoglycans"],
    dosage: {
      tea: "3-9g daily",
      decoction: "3-6g for 20-30 minutes",
      powder: "1-3g twice daily",
      tincture: "10-20 drops 2-3 times daily",
    },
    contraindications: ["high fever", "acute infection", "pregnancy"],
    interactions: [
      "May interact with blood thinners",
      "Avoid with stimulants",
    ],
    sideEffects: ["insomnia if taken late", "headache", "digestive upset"],
    researchStudies: [
      { title: "Effects of Ginseng on Immune Function", year: 2019 },
      { title: "Korean Red Ginseng for Cognitive Enhancement", year: 2021 },
    ],
    season: "year-round",
    traditionalUse: "Supreme tonic for rebuilding vital energy (qi)",
    preparation: "Steep in hot water for 5-10 minutes or simmer for 20 minutes",
    storageInstructions: "Store in cool, dry place away from direct sunlight",
    priceRange: "$15-50 per ounce",
    availability: "common",
    scientificName: "Panax ginseng C.A. Meyer",
    partUsed: "Root",
  },
  {
    id: "korean-mugwort-002",
    name: "Korean Mugwort",
    koreanName: "쑥 (Ssuk)",
    system: "korean",
    category: "Women's Health & Cleansing",
    energetics: {
      temperature: "warm",
      taste: ["bitter", "pungent"],
    },
    benefits: [
      "Regulates menstrual cycle",
      "Relieves menstrual cramps",
      "Supports uterine health",
      "Detoxifies the liver",
      "Improves digestion",
      "Eases joint pain",
    ],
    symptoms: [
      "irregular periods",
      "menstrual cramps",
      "poor digestion",
      "liver stagnation",
      "joint pain",
      "bloating",
    ],
    activeCompounds: ["thujone", "cinole", "camphor", "tannins"],
    dosage: {
      tea: "2-5g daily",
      decoction: "5-10g for 15-20 minutes",
      powder: "1-2g twice daily",
      tincture: "5-15 drops 2-3 times daily",
    },
    contraindications: [
      "pregnancy",
      "excessive bleeding disorders",
      "hypersensitivity to mugwort",
    ],
    interactions: ["May increase bleeding with anticoagulants"],
    sideEffects: ["uterine stimulation", "allergic reaction in sensitive individuals"],
    researchStudies: [
      { title: "Mugwort in Traditional Korean Medicine", year: 2018 },
      { title: "Menstrual Regulation with Artemisia Species", year: 2020 },
    ],
    season: "spring",
    traditionalUse: "Warms the uterus and moves stagnant blood",
    preparation: "Decoct or make into tea, strain well",
    storageInstructions: "Dry thoroughly and store in sealed container",
    priceRange: "$3-8 per ounce",
    availability: "common",
    scientificName: "Artemisia princeps Pamp.",
    partUsed: "Leaf",
  },
  {
    id: "korean-astragalus-003",
    name: "Astragalus (Huang Qi)",
    koreanName: "황기 (Hwanggi)",
    system: "korean",
    category: "Immune Support",
    energetics: {
      temperature: "neutral",
      taste: ["sweet"],
    },
    benefits: [
      "Strengthens immune system",
      "Increases white blood cell production",
      "Improves recovery after illness",
      "Enhances energy and endurance",
      "Supports respiratory health",
      "Aids wound healing",
    ],
    symptoms: [
      "weak immunity",
      "frequent colds",
      "low energy",
      "slow wound healing",
      "shortness of breath",
    ],
    activeCompounds: ["polysaccharides", "astragaloside IV", "saponins"],
    dosage: {
      tea: "9-15g daily",
      decoction: "10-15g for 30-40 minutes",
      powder: "3-9g daily",
      tincture: "20-30 drops 2-3 times daily",
    },
    contraindications: ["acute infections", "excessive sweating"],
    interactions: ["May reduce effectiveness of some immunosuppressants"],
    sideEffects: ["generally well-tolerated", "rare mild digestive upset"],
    researchStudies: [
      { title: "Astragalus Polysaccharides on Immune Function", year: 2021 },
      { title: "Astragalus for Prevention of Upper Respiratory Infection", year: 2019 },
    ],
    season: "autumn",
    traditionalUse: "Fortifies protective qi (wei qi) to prevent disease",
    preparation: "Long decoction 30-40 minutes, often used in soups",
    storageInstructions: "Store in cool, dry place, protected from insects",
    priceRange: "$5-15 per ounce",
    availability: "common",
    scientificName: "Astragalus membranaceus Fisch.",
    partUsed: "Root",
  },
  {
    id: "korean-rehmannia-004",
    name: "Rehmannia (Suk Di Huang)",
    koreanName: "숙지황 (Suk Ji Hwang)",
    system: "korean",
    category: "Blood & Yin Tonics",
    energetics: {
      temperature: "slightly warm",
      taste: ["sweet"],
    },
    benefits: [
      "Nourishes blood",
      "Tonifies yin energy",
      "Improves complexion",
      "Supports bone health",
      "Addresses menstrual issues",
      "Supports kidney function",
    ],
    symptoms: [
      "pale complexion",
      "dizziness",
      "irregular periods",
      "dry skin",
      "constipation",
      "poor memory",
    ],
    activeCompounds: ["iridoid glycosides", "sugars", "amino acids"],
    dosage: {
      tea: "6-12g daily",
      decoction: "9-15g for 30 minutes",
      powder: "2-4g twice daily",
      tincture: "15-30 drops 2-3 times daily",
    },
    contraindications: ["poor digestion", "loose stools", "acute infections"],
    interactions: ["May slow digestion"],
    sideEffects: ["may cause loose stools in some individuals"],
    researchStudies: [
      { title: "Rehmannia in Blood Tonification", year: 2020 },
      { title: "Rehmannia for Menopausal Symptoms", year: 2019 },
    ],
    season: "year-round",
    traditionalUse: "Enriches blood and nourishes bone marrow",
    preparation: "Decoct for 30 minutes, often used in formulas",
    storageInstructions: "Store in cool, dry conditions",
    priceRange: "$8-20 per ounce",
    availability: "moderate",
    scientificName: "Rehmannia glutinosa Libosch. var. purpurea Makino",
    partUsed: "Root tuber",
  },
  {
    id: "korean-chrysanthemum-005",
    name: "Chrysanthemum Flower",
    koreanName: "국화 (Gukhwa)",
    system: "korean",
    category: "Cooling & Detoxification",
    energetics: {
      temperature: "cool",
      taste: ["sweet", "bitter"],
    },
    benefits: [
      "Cools body heat",
      "Clears eyes",
      "Reduces inflammation",
      "Clears liver fire",
      "Supports eye health",
      "Calms nervous system",
    ],
    symptoms: [
      "heat symptoms",
      "eye fatigue",
      "headache",
      "sore throat",
      "irritability",
      "insomnia",
    ],
    activeCompounds: ["flavonoids", "volatile oils", "caffeoylquinic acid"],
    dosage: {
      tea: "3-10g daily",
      decoction: "5-10g for 5-10 minutes",
      powder: "2-3g twice daily",
      tincture: "10-20 drops 2-3 times daily",
    },
    contraindications: ["cold constitution", "excessive yin deficiency"],
    interactions: ["Generally no significant interactions"],
    sideEffects: ["rare, generally well-tolerated"],
    researchStudies: [
      { title: "Chrysanthemum for Eye Health", year: 2020 },
      { title: "Anti-inflammatory Effects of Chrysanthemum", year: 2019 },
    ],
    season: "summer",
    traditionalUse: "Cools liver heat and brightens the eyes",
    preparation: "Steep 3-5 minutes in hot water, or cold brew",
    storageInstructions: "Store in sealed container away from moisture",
    priceRange: "$4-12 per ounce",
    availability: "common",
    scientificName: "Chrysanthemum morifolium Ramat.",
    partUsed: "Flower",
  },
  {
    id: "korean-eucommia-006",
    name: "Eucommia Bark",
    koreanName: "두충 (Du Chung)",
    system: "korean",
    category: "Joint & Bone Health",
    energetics: {
      temperature: "warm",
      taste: ["sweet"],
    },
    benefits: [
      "Strengthens bones and joints",
      "Supports lower back health",
      "Improves circulation",
      "Tonifies kidneys",
      "Supports pregnancy",
      "Reduces joint pain",
    ],
    symptoms: [
      "lower back pain",
      "weak knees",
      "joint pain",
      "poor bone health",
      "miscarriage tendency",
      "high blood pressure",
    ],
    activeCompounds: ["aucubin", "geniposidic acid", "chlorogenic acid"],
    dosage: {
      tea: "6-12g daily",
      decoction: "9-15g for 30 minutes",
      powder: "2-4g twice daily",
      tincture: "20-30 drops 2-3 times daily",
    },
    contraindications: ["kidney yin deficiency", "pregnancy complications"],
    interactions: ["May interact with blood pressure medications"],
    sideEffects: ["dizziness in some individuals"],
    researchStudies: [
      { title: "Eucommia for Bone Density", year: 2021 },
      { title: "Eucommia and Lower Back Pain", year: 2020 },
    ],
    season: "year-round",
    traditionalUse: "Tonifies liver and kidneys, strengthens bones",
    preparation: "Decoct 30 minutes, often combined with other herbs",
    storageInstructions: "Store in cool, dry place",
    priceRange: "$6-14 per ounce",
    availability: "moderate",
    scientificName: "Eucommia ulmoides Oliv.",
    partUsed: "Bark",
  },
  {
    id: "korean-goji-007",
    name: "Goji Berry",
    koreanName: "구기자 (Gugi Ja)",
    system: "korean",
    category: "Nutritive Tonic",
    energetics: {
      temperature: "neutral",
      taste: ["sweet"],
    },
    benefits: [
      "Nourishes blood and yin",
      "Improves vision",
      "Boosts immune function",
      "Supports reproductive health",
      "Enhances energy",
      "Supports longevity",
    ],
    symptoms: [
      "blurred vision",
      "low energy",
      "weak immunity",
      "infertility",
      "aging signs",
      "night sweats",
    ],
    activeCompounds: [
      "polysaccharides",
      "zeaxanthin",
      "betaine",
      "amino acids",
    ],
    dosage: {
      tea: "6-12g daily",
      decoction: "5-10g for 10 minutes",
      powder: "3-6g daily",
      tincture: "20-30 drops 2-3 times daily",
    },
    contraindications: ["spleen deficiency with diarrhea", "high sugar content"],
    interactions: ["May interact with anticoagulants"],
    sideEffects: ["generally well-tolerated", "rare: warming effect"],
    researchStudies: [
      { title: "Goji Polysaccharides on Vision", year: 2020 },
      { title: "Goji Berry and Immune Function", year: 2021 },
    ],
    season: "year-round",
    traditionalUse: "Nourishes liver, kidney and lung yin",
    preparation: "Steep in hot water, eat the berries, or decoct",
    storageInstructions: "Store in cool, dry place away from direct light",
    priceRange: "$4-10 per ounce",
    availability: "common",
    scientificName: "Lycium barbarum L.",
    partUsed: "Fruit",
  },
  {
    id: "korean-cordyceps-008",
    name: "Cordyceps Mushroom",
    koreanName: "동충하초 (Dong Chung Ha Cho)",
    system: "korean",
    category: "Energy & Vitality",
    energetics: {
      temperature: "neutral",
      taste: ["sweet"],
    },
    benefits: [
      "Increases energy and stamina",
      "Enhances athletic performance",
      "Supports respiratory function",
      "Improves oxygen utilization",
      "Strengthens immune system",
      "Supports recovery",
    ],
    symptoms: [
      "fatigue",
      "low stamina",
      "shortness of breath",
      "poor recovery",
      "weak immunity",
      "asthma",
    ],
    activeCompounds: [
      "cordycepin",
      "adenosine",
      "polysaccharides",
      "nucleosides",
    ],
    dosage: {
      tea: "3-9g daily",
      decoction: "5-10g for 30-40 minutes",
      powder: "1-3g twice daily",
      tincture: "10-20 drops 2-3 times daily",
    },
    contraindications: [
      "not suitable during acute infections",
      "pregnancy",
    ],
    interactions: ["May interact with anticoagulants"],
    sideEffects: ["generally well-tolerated", "rare: mild stimulation"],
    researchStudies: [
      { title: "Cordyceps for Athletic Performance", year: 2020 },
      { title: "Cordyceps and Oxygen Utilization", year: 2021 },
    ],
    season: "year-round",
    traditionalUse: "Tonifies lung and kidney qi, increases vitality",
    preparation: "Decoct 30-40 minutes, often combined with other tonics",
    storageInstructions: "Store in cool, dry place",
    priceRange: "$20-80 per ounce",
    availability: "moderate",
    scientificName: "Ophiocordyceps sinensis",
    partUsed: "Fruiting body",
  },
  {
    id: "korean-hawthorn-009",
    name: "Hawthorn Berry",
    koreanName: "산사나무 (Sansa Namu)",
    system: "korean",
    category: "Cardiovascular Support",
    energetics: {
      temperature: "neutral",
      taste: ["sour", "sweet"],
    },
    benefits: [
      "Supports heart health",
      "Improves circulation",
      "Regulates blood pressure",
      "Aids digestion",
      "Improves blood flow",
      "Reduces cholesterol",
    ],
    symptoms: [
      "palpitations",
      "high blood pressure",
      "poor circulation",
      "chest tightness",
      "poor digestion",
      "high cholesterol",
    ],
    activeCompounds: [
      "flavonoids",
      "proanthocyanidins",
      "vitexin",
      "hyperoside",
    ],
    dosage: {
      tea: "3-10g daily",
      decoction: "5-15g for 20-30 minutes",
      powder: "2-3g twice daily",
      tincture: "20-30 drops 2-3 times daily",
    },
    contraindications: [
      "low blood pressure",
      "not suitable for heart medication interactions",
    ],
    interactions: ["May interact with heart medications"],
    sideEffects: ["rare", "generally well-tolerated"],
    researchStudies: [
      { title: "Hawthorn for Cardiovascular Health", year: 2020 },
      { title: "Hawthorn and Blood Pressure Regulation", year: 2021 },
    ],
    season: "autumn",
    traditionalUse: "Moves liver qi and supports heart function",
    preparation: "Decoct 20-30 minutes or steep in hot water",
    storageInstructions: "Store in sealed container away from moisture",
    priceRange: "$3-8 per ounce",
    availability: "common",
    scientificName: "Crataegus cuneata Siebold ex Lindl.",
    partUsed: "Fruit",
  },
  {
    id: "korean-red-ginseng-010",
    name: "Red Ginseng Extract",
    koreanName: "홍삼정 (Hong Sam Jeong)",
    system: "korean",
    category: "Premium Energy Tonic",
    energetics: {
      temperature: "warm",
      taste: ["sweet", "bitter"],
    },
    benefits: [
      "Maximum energy boost",
      "Enhanced vitality",
      "Stress resilience",
      "Improved endurance",
      "Supports mental clarity",
      "Enhanced sexual function",
    ],
    symptoms: [
      "severe fatigue",
      "burnout",
      "extreme stress",
      "low libido",
      "mental fog",
      "weakness",
    ],
    activeCompounds: [
      "high-concentration ginsenosides",
      "polysaccharides",
      "organic acids",
    ],
    dosage: {
      tea: "1-3g daily",
      decoction: "2-6g daily",
      powder: "0.5-1g twice daily",
      tincture: "5-10 drops 2-3 times daily",
    },
    contraindications: ["high fever", "acute infections", "anxiety"],
    interactions: ["May interact with stimulants"],
    sideEffects: ["warming effect", "insomnia if taken late"],
    researchStudies: [
      { title: "Red Ginseng Extract for Energy", year: 2021 },
      { title: "Red Ginseng and Mental Performance", year: 2020 },
    ],
    season: "winter",
    traditionalUse: "Supreme qi tonic, more potent than regular ginseng",
    preparation: "Steep 3-5 minutes or take as directed",
    storageInstructions: "Store in cool, dry place",
    priceRange: "$30-100 per ounce",
    availability: "moderate",
    scientificName: "Panax ginseng C.A. Meyer (processed)",
    partUsed: "Root extract",
  },
  {
    id: "korean-notoginseng-011",
    name: "Notoginseng (Tian Qi)",
    koreanName: "삼칠근 (Samchil Geun)",
    system: "korean",
    category: "Blood & Trauma",
    energetics: {
      temperature: "neutral",
      taste: ["sweet", "bitter"],
    },
    benefits: [
      "Stops bleeding",
      "Promotes blood circulation",
      "Relieves pain",
      "Heals bruises",
      "Supports wound healing",
      "Reduces inflammation",
    ],
    symptoms: [
      "bleeding",
      "bruising",
      "pain",
      "trauma",
      "blood stagnation",
      "swelling",
    ],
    activeCompounds: ["saponins", "notoginsenosides", "polysaccharides"],
    dosage: {
      tea: "3-6g daily",
      decoction: "2-3g for 30 minutes",
      powder: "1-2g 2-3 times daily",
      tincture: "10-15 drops 2-3 times daily",
    },
    contraindications: [
      "bleeding disorders",
      "anticoagulant use",
      "pregnancy",
    ],
    interactions: ["May interact with anticoagulants"],
    sideEffects: ["mouth numbness in high doses"],
    researchStudies: [
      { title: "Notoginseng for Hemorrhage", year: 2019 },
      { title: "Notoginseng and Pain Relief", year: 2020 },
    ],
    season: "year-round",
    traditionalUse: "Stops bleeding and invigorates blood",
    preparation: "Powder taken with water or decocted",
    storageInstructions: "Store in cool, dry place",
    priceRange: "$12-30 per ounce",
    availability: "moderate",
    scientificName: "Panax notoginseng (Burk.) F.H. Chen ex C.Y. Wu",
    partUsed: "Root",
  },
  {
    id: "korean-dang-gui-012",
    name: "Dong Quai (Tang Kui)",
    koreanName: "당귀 (Dang Gui)",
    system: "korean",
    category: "Women's Tonic",
    energetics: {
      temperature: "warm",
      taste: ["sweet", "pungent"],
    },
    benefits: [
      "Nourishes blood",
      "Regulates menstruation",
      "Relieves menstrual cramps",
      "Supports fertility",
      "Moistens intestines",
      "Promotes circulation",
    ],
    symptoms: [
      "irregular periods",
      "menstrual cramps",
      "pale complexion",
      "infertility",
      "constipation",
      "poor circulation",
    ],
    activeCompounds: [
      "ligustilide",
      "phthalides",
      "coumarins",
      "polysaccharides",
    ],
    dosage: {
      tea: "6-12g daily",
      decoction: "9-15g for 30 minutes",
      powder: "2-4g twice daily",
      tincture: "20-30 drops 2-3 times daily",
    },
    contraindications: [
      "heavy menstrual bleeding",
      "diarrhea",
      "pregnancy",
    ],
    interactions: ["May increase bleeding with anticoagulants"],
    sideEffects: ["photosensitivity", "mild stomach upset"],
    researchStudies: [
      { title: "Dong Quai for Menstrual Health", year: 2020 },
      { title: "Dong Quai and Female Fertility", year: 2019 },
    ],
    season: "year-round",
    traditionalUse: "Female ginseng, tonifies and invigorates blood",
    preparation: "Decoct 30 minutes, often used with other herbs",
    storageInstructions: "Store in cool, dry place",
    priceRange: "$4-10 per ounce",
    availability: "common",
    scientificName: "Angelica sinensis (Oliv.) Diels",
    partUsed: "Root",
  },
  {
    id: "korean-licorice-013",
    name: "Licorice Root",
    koreanName: "감초 (Gamcho)",
    system: "korean",
    category: "Harmonizing & Soothing",
    energetics: {
      temperature: "neutral",
      taste: ["sweet"],
    },
    benefits: [
      "Soothes throat and lungs",
      "Harmonizes other herbs",
      "Supports adrenal function",
      "Reduces inflammation",
      "Eases cough",
      "Supports digestion",
    ],
    symptoms: [
      "sore throat",
      "cough",
      "cough",
      "stomach ulcers",
      "stress",
      "fatigue",
      "low cortisol",
    ],
    activeCompounds: ["glycyrrhizin", "flavonoids", "coumarins"],
    dosage: {
      tea: "2-6g daily",
      decoction: "2-4g for 15 minutes",
      powder: "1-2g twice daily",
      tincture: "5-10 drops 2-3 times daily",
    },
    contraindications: [
      "high blood pressure",
      "edema",
      "pregnancy",
      "hypokalemia",
    ],
    interactions: ["May interact with diuretics and corticosteroids"],
    sideEffects: ["water retention in high doses", "hypertension"],
    researchStudies: [
      { title: "Licorice for Respiratory Health", year: 2020 },
      { title: "Licorice and Adrenal Support", year: 2021 },
    ],
    season: "year-round",
    traditionalUse: "Harmonizes all herbs, supports stomach",
    preparation: "Decoct for 15 minutes with other herbs",
    storageInstructions: "Store in sealed container",
    priceRange: "$2-6 per ounce",
    availability: "common",
    scientificName: "Glycyrrhiza glabra L.",
    partUsed: "Root",
  },
  {
    id: "korean-ginger-014",
    name: "Dried Ginger",
    koreanName: "생강 (Saengang) / 건강 (Geongang)",
    system: "korean",
    category: "Warming & Digestive",
    energetics: {
      temperature: "hot",
      taste: ["pungent", "sweet"],
    },
    benefits: [
      "Warms digestive system",
      "Relieves nausea",
      "Eases bloating",
      "Improves circulation",
      "Relieves joint pain",
      "Anti-inflammatory",
    ],
    symptoms: [
      "nausea",
      "vomiting",
      "cold stomach",
      "poor digestion",
      "joint pain",
      "arthritis",
      "poor circulation",
    ],
    activeCompounds: ["gingerols", "shogaols", "paradols"],
    dosage: {
      tea: "2-6g daily",
      decoction: "3-10g for 15-20 minutes",
      powder: "1-2g 2-3 times daily",
      tincture: "10-20 drops 2-3 times daily",
    },
    contraindications: ["yin deficiency with heat", "bleeding disorders"],
    interactions: ["May interact with anticoagulants"],
    sideEffects: ["heartburn in sensitive individuals"],
    researchStudies: [
      { title: "Ginger for Nausea and Digestion", year: 2020 },
      { title: "Ginger and Inflammation", year: 2021 },
    ],
    season: "winter",
    traditionalUse: "Warms middle burner, stops vomiting",
    preparation: "Steep 5-10 minutes or decoct 15-20 minutes",
    storageInstructions: "Store in cool, dry place",
    priceRange: "$2-5 per ounce",
    availability: "common",
    scientificName: "Zingiber officinale Roscoe",
    partUsed: "Rhizome",
  },
  {
    id: "korean-dioscorea-015",
    name: "Chinese Yam (Dioscorea)",
    koreanName: "산약 (Sanyak)",
    system: "korean",
    category: "Nutritive Tonic",
    energetics: {
      temperature: "neutral",
      taste: ["sweet"],
    },
    benefits: [
      "Strengthens spleen",
      "Improves digestion",
      "Tonifies lungs",
      "Stops diarrhea",
      "Supports blood sugar",
      "Builds energy",
    ],
    symptoms: [
      "weak digestion",
      "diarrhea",
      "fatigue",
      "weak appetite",
      "respiratory issues",
      "blood sugar imbalance",
    ],
    activeCompounds: [
      "allantoin",
      "polysaccharides",
      "amino acids",
      "mucilage",
    ],
    dosage: {
      tea: "9-18g daily",
      decoction: "12-18g for 40 minutes",
      powder: "3-6g twice daily",
      tincture: "20-30 drops 2-3 times daily",
    },
    contraindications: ["constipation with heat", "stagnation"],
    interactions: ["Generally no significant interactions"],
    sideEffects: ["very mild", "generally well-tolerated"],
    researchStudies: [
      { title: "Dioscorea for Digestive Support", year: 2020 },
      { title: "Dioscorea and Blood Sugar Balance", year: 2021 },
    ],
    season: "year-round",
    traditionalUse: "Tonifies spleen and stomach, builds qi and yin",
    preparation: "Decoct 40 minutes with other herbs",
    storageInstructions: "Store in cool, dry place",
    priceRange: "$3-8 per ounce",
    availability: "common",
    scientificName: "Dioscorea opposite Thunb.",
    partUsed: "Rhizome",
  },
  {
    id: "korean-angelica-016",
    name: "Angelica Root",
    koreanName: "흰층층이 (Hwinsacheung Chung)",
    system: "korean",
    category: "Circulation & Pain",
    energetics: {
      temperature: "warm",
      taste: ["pungent", "bitter"],
    },
    benefits: [
      "Invigorates blood",
      "Relieves pain",
      "Supports circulation",
      "Eases joint pain",
      "Reduces arthritis",
      "Promotes healing",
    ],
    symptoms: [
      "blood stagnation",
      "pain",
      "poor circulation",
      "arthritis",
      "bruising",
      "trauma",
    ],
    activeCompounds: ["decursinol", "coumarin", "umbelliferone"],
    dosage: {
      tea: "6-12g daily",
      decoction: "9-15g for 30 minutes",
      powder: "2-3g twice daily",
      tincture: "20-30 drops 2-3 times daily",
    },
    contraindications: ["bleeding disorders", "diarrhea"],
    interactions: ["May increase bleeding with anticoagulants"],
    sideEffects: ["rare", "photosensitivity in some"],
    researchStudies: [
      { title: "Angelica for Circulation", year: 2020 },
      { title: "Angelica and Pain Relief", year: 2019 },
    ],
    season: "year-round",
    traditionalUse: "Invigorates blood and moves qi",
    preparation: "Decoct 30 minutes with other herbs",
    storageInstructions: "Store in cool, dry place",
    priceRange: "$4-10 per ounce",
    availability: "common",
    scientificName: "Angelica dahurica (Fisch.) Benth. ex Hook.",
    partUsed: "Root",
  },
  {
    id: "korean-shiitake-017",
    name: "Shiitake Mushroom",
    koreanName: "표고버섯 (Pyogo Beoseot)",
    system: "korean",
    category: "Immune & Nutritive",
    energetics: {
      temperature: "neutral",
      taste: ["sweet"],
    },
    benefits: [
      "Strengthens immune system",
      "Supports bone health",
      "Reduces cholesterol",
      "Anti-tumor properties",
      "Improves circulation",
      "Nutrient rich",
    ],
    symptoms: [
      "weak immunity",
      "high cholesterol",
      "poor bone health",
      "cancer prevention",
      "low energy",
      "poor appetite",
    ],
    activeCompounds: [
      "lentinan",
      "beta-glucans",
      "polysaccharides",
      "vitamins",
    ],
    dosage: {
      tea: "3-10g dried daily",
      decoction: "5-15g for 30 minutes",
      powder: "2-3g twice daily",
      tincture: "20-30 drops 2-3 times daily",
    },
    contraindications: ["generally no contraindications"],
    interactions: ["May interact with immunosuppressants"],
    sideEffects: ["rare", "very well-tolerated"],
    researchStudies: [
      { title: "Shiitake Lentinan for Immune Function", year: 2021 },
      { title: "Shiitake and Cholesterol Reduction", year: 2020 },
    ],
    season: "year-round",
    traditionalUse: "Tonifies qi and strengthens immunity",
    preparation: "Decoct 30 minutes or add to soups",
    storageInstructions: "Store in sealed container",
    priceRange: "$5-15 per ounce",
    availability: "common",
    scientificName: "Lentinula edodes (Berk.) Pegler",
    partUsed: "Fruiting body",
  },
  {
    id: "korean-lycium-018",
    name: "Lycium Leaf",
    koreanName: "구기자잎 (Gugi Ja Ip)",
    system: "korean",
    category: "Yin Tonic",
    energetics: {
      temperature: "neutral",
      taste: ["sweet", "bitter"],
    },
    benefits: [
      "Nourishes liver yin",
      "Improves vision",
      "Supports kidney function",
      "Brightens eyes",
      "Improves complexion",
      "Supports immune function",
    ],
    symptoms: [
      "blurred vision",
      "dry eyes",
      "liver yin deficiency",
      "dizziness",
      "poor skin",
      "night sweats",
    ],
    activeCompounds: ["polysaccharides", "zeaxanthin", "betaine"],
    dosage: {
      tea: "3-10g daily",
      decoction: "5-10g for 15 minutes",
      powder: "2-3g twice daily",
      tincture: "15-25 drops 2-3 times daily",
    },
    contraindications: ["spleen deficiency with loose stools"],
    interactions: ["Generally no significant interactions"],
    sideEffects: ["very rare", "generally well-tolerated"],
    researchStudies: [
      { title: "Lycium Leaf for Vision", year: 2020 },
      { title: "Lycium and Eye Health", year: 2021 },
    ],
    season: "year-round",
    traditionalUse: "Nourishes yin of liver and kidney",
    preparation: "Steep in hot water or decoct",
    storageInstructions: "Store in sealed container away from moisture",
    priceRange: "$3-8 per ounce",
    availability: "common",
    scientificName: "Lycium barbarum L.",
    partUsed: "Leaf",
  },
  {
    id: "korean-poria-019",
    name: "Poria Fungus",
    koreanName: "복령 (Bokryeong)",
    system: "korean",
    category: "Spleen & Water Balance",
    energetics: {
      temperature: "neutral",
      taste: ["sweet"],
    },
    benefits: [
      "Strengthens spleen",
      "Removes excess moisture",
      "Promotes digestion",
      "Calms heart",
      "Improves sleep",
      "Diuretic",
    ],
    symptoms: [
      "bloating",
      "water retention",
      "poor digestion",
      "loose stools",
      "insomnia",
      "anxiety",
      "edema",
    ],
    activeCompounds: ["polysaccharides", "triterpenes", "beta-glucans"],
    dosage: {
      tea: "9-15g daily",
      decoction: "12-18g for 30 minutes",
      powder: "3-6g twice daily",
      tincture: "20-30 drops 2-3 times daily",
    },
    contraindications: ["kidney qi deficiency", "yin deficiency"],
    interactions: ["Generally no significant interactions"],
    sideEffects: ["very rare", "generally well-tolerated"],
    researchStudies: [
      { title: "Poria for Spleen Support", year: 2020 },
      { title: "Poria and Water Metabolism", year: 2019 },
    ],
    season: "year-round",
    traditionalUse: "Strengthens spleen and eliminates dampness",
    preparation: "Decoct 30 minutes with other herbs",
    storageInstructions: "Store in sealed, dry container",
    priceRange: "$3-8 per ounce",
    availability: "common",
    scientificName: "Wolfiporia cocos (F.A. Wolf) Ryvarden & Melo",
    partUsed: "Sclerotium",
  },
  {
    id: "korean-ho-shou-wu-020",
    name: "He Shou Wu (Fo-Ti)",
    koreanName: "하수오 (Ha Su O)",
    system: "korean",
    category: "Hair & Longevity",
    energetics: {
      temperature: "neutral",
      taste: ["bitter", "sweet"],
    },
    benefits: [
      "Darkens hair",
      "Supports hair growth",
      "Tonifies blood",
      "Supports liver function",
      "Promotes longevity",
      "Improves complexion",
    ],
    symptoms: [
      "premature graying",
      "hair loss",
      "weak blood",
      "poor skin",
      "aging",
      "liver stagnation",
    ],
    activeCompounds: ["emodin", "polysaccharides", "lecithin"],
    dosage: {
      tea: "9-15g daily",
      decoction: "12-15g for 45 minutes",
      powder: "2-3g twice daily",
      tincture: "20-30 drops 2-3 times daily",
    },
    contraindications: ["diarrhea", "loose stools", "pregnancy"],
    interactions: ["May interact with heart medications"],
    sideEffects: [
      "loose stools in sensitive individuals",
      "skin rash in rare cases",
    ],
    researchStudies: [
      { title: "He Shou Wu for Hair Pigmentation", year: 2020 },
      { title: "He Shou Wu and Hair Growth", year: 2019 },
    ],
    season: "year-round",
    traditionalUse: "Tonifies liver and kidneys, darkens hair",
    preparation: "Decoct 45 minutes with other herbs",
    storageInstructions: "Store in cool, dry place",
    priceRange: "$4-10 per ounce",
    availability: "common",
    scientificName: "Fallopia multiflora (L.) Harald.",
    partUsed: "Rhizome",
  },
]

export const ayurvedicHerbs: HerbalRemedyDetailed[] = [
  {
    id: "ayurvedic-ashwagandha-001",
    name: "Ashwagandha",
    sanskritName: "वाजीकरण (Vajikarana)",
    system: "ayurvedic",
    category: "Adaptogenic Tonic",
    energetics: {
      temperature: "warm",
      taste: ["bitter", "pungent", "sweet"],
      dosha: "vata",
    },
    benefits: [
      "Reduces stress and anxiety",
      "Enhances sexual vitality",
      "Improves sleep quality",
      "Builds muscle and strength",
      "Supports immune function",
      "Improves focus and memory",
    ],
    symptoms: [
      "stress",
      "anxiety",
      "insomnia",
      "fatigue",
      "low sexual function",
      "weak immunity",
      "poor concentration",
    ],
    activeCompounds: ["withanolides", "alkaloids", "phenolic compounds"],
    dosage: {
      tea: "3-6g daily",
      decoction: "3-5g for 15-20 minutes",
      powder: "1-2g twice daily with warm milk",
      tincture: "10-20 drops 2-3 times daily",
    },
    contraindications: [
      "pregnancy",
      "excessive heat",
      "acute inflammation",
    ],
    interactions: ["May interact with sedatives", "May interact with thyroid medications"],
    sideEffects: [
      "sedation in high doses",
      "mild gastrointestinal upset",
      "headache",
    ],
    researchStudies: [
      { title: "Ashwagandha for Stress and Anxiety", year: 2021 },
      { title: "Withania somnifera and Sexual Function", year: 2020 },
      { title: "Ashwagandha and Sleep Quality", year: 2019 },
    ],
    season: "winter",
    traditionalUse: "Balances Vata, promotes strength and longevity",
    preparation: "Steep in hot milk with honey, or decoct",
    storageInstructions: "Store in sealed container away from moisture",
    priceRange: "$8-20 per ounce",
    availability: "common",
    scientificName: "Withania somnifera (L.) Dunal",
    partUsed: "Root",
  },
  {
    id: "ayurvedic-turmeric-002",
    name: "Turmeric",
    sanskritName: "हल्दी (Haldi)",
    system: "ayurvedic",
    category: "Anti-inflammatory",
    energetics: {
      temperature: "warm",
      taste: ["bitter", "pungent"],
      dosha: "pitta",
    },
    benefits: [
      "Powerful anti-inflammatory",
      "Supports liver function",
      "Reduces joint pain",
      "Purifies blood",
      "Improves digestion",
      "Supports skin health",
    ],
    symptoms: [
      "inflammation",
      "joint pain",
      "arthritis",
      "liver congestion",
      "skin conditions",
      "digestive issues",
      "poor circulation",
    ],
    activeCompounds: ["curcumin", "demethoxycurcumin", "volatile oils"],
    dosage: {
      tea: "1-3g daily",
      decoction: "2-4g for 10 minutes",
      powder: "1-2g twice daily with fat",
      tincture: "10-20 drops 2-3 times daily",
    },
    contraindications: [
      "gallstones",
      "yin deficiency",
      "blood deficiency",
      "pregnancy",
    ],
    interactions: ["May interact with blood thinners", "May inhibit iron absorption"],
    sideEffects: [
      "bitter taste",
      "mild gastrointestinal upset",
      "photosensitivity in high doses",
    ],
    researchStudies: [
      { title: "Curcumin for Inflammation", year: 2021 },
      { title: "Turmeric and Joint Health", year: 2020 },
      { title: "Curcumin for Cognitive Support", year: 2021 },
    ],
    season: "year-round",
    traditionalUse: "Balances Pitta, cleanses blood and channels",
    preparation: "Combine with black pepper and fat for absorption",
    storageInstructions: "Store in cool, dry place away from light",
    priceRange: "$2-8 per ounce",
    availability: "common",
    scientificName: "Curcuma longa L.",
    partUsed: "Rhizome",
  },
  {
    id: "ayurvedic-brahmi-003",
    name: "Brahmi",
    sanskritName: "ब्राह्मी (Brahmi)",
    system: "ayurvedic",
    category: "Brain & Nervous System",
    energetics: {
      temperature: "cool",
      taste: ["bitter", "sweet"],
      dosha: "pitta",
    },
    benefits: [
      "Enhances memory and learning",
      "Reduces anxiety",
      "Supports brain function",
      "Calms nervous system",
      "Improves focus",
      "Supports meditative states",
    ],
    symptoms: [
      "poor memory",
      "anxiety",
      "racing thoughts",
      "ADHD symptoms",
      "stress",
      "restlessness",
      "brain fog",
    ],
    activeCompounds: ["bacoside A and B", "alkaloids", "saponins"],
    dosage: {
      tea: "3-6g daily",
      decoction: "5-10g for 15 minutes",
      powder: "1-2g twice daily",
      tincture: "10-20 drops 2-3 times daily",
    },
    contraindications: ["slow digestion", "cold and dampness"],
    interactions: ["May increase sedation with other sedatives"],
    sideEffects: ["stomach upset in some", "skin rash in rare cases"],
    researchStudies: [
      { title: "Brahmi for Memory Enhancement", year: 2021 },
      { title: "Bacopa monnieri and Cognitive Function", year: 2020 },
      { title: "Brahmi for Anxiety Disorders", year: 2019 },
    ],
    season: "summer",
    traditionalUse: "Medhya rasayana, enhances intelligence and memory",
    preparation: "Decoct or make into ghee, or consume as powder with warm water",
    storageInstructions: "Store in cool, dry place",
    priceRange: "$8-15 per ounce",
    availability: "common",
    scientificName: "Bacopa monniera (L.) Wettst.",
    partUsed: "Whole plant",
  },
  {
    id: "ayurvedic-triphala-004",
    name: "Triphala",
    sanskritName: "त्रिफला (Triphala)",
    system: "ayurvedic",
    category: "Digestive Tonic",
    energetics: {
      temperature: "balanced",
      taste: ["all six tastes"],
      dosha: "tridoshic",
    },
    benefits: [
      "Balances all three doshas",
      "Supports digestion",
      "Gentle laxative",
      "Removes toxins",
      "Supports eye health",
      "Strengthens immunity",
    ],
    symptoms: [
      "constipation",
      "weak digestion",
      "toxin buildup",
      "inflammation",
      "poor immunity",
      "weak eyes",
      "poor absorption",
    ],
    activeCompounds: [
      "gallic acid",
      "ellagic acid",
      "anthraquinones",
      "polyphenols",
    ],
    dosage: {
      tea: "3-6g daily",
      decoction: "2-5g in warm water overnight",
      powder: "1-2g at bedtime",
      tincture: "10-15 drops 2-3 times daily",
    },
    contraindications: ["pregnancy", "severe dehydration"],
    interactions: ["May reduce absorption of medications"],
    sideEffects: ["loose stools initially", "mild cramping"],
    researchStudies: [
      { title: "Triphala for Digestive Health", year: 2020 },
      { title: "Triphala and Antioxidant Properties", year: 2021 },
      { title: "Triphala as Detoxification", year: 2019 },
    ],
    season: "year-round",
    traditionalUse: "Tridoshic formula for digestive health",
    preparation: "Soak overnight in water or decoct gently",
    storageInstructions: "Store in sealed container",
    priceRange: "$3-10 per ounce",
    availability: "common",
    scientificName: "Combination of Emblica officinalis, Terminalia bellirica, Terminalia chebula",
    partUsed: "Fruits",
  },
  {
    id: "ayurvedic-ginger-005",
    name: "Fresh Ginger",
    sanskritName: "आर्द्र अदरक (Ardra Adrak)",
    system: "ayurvedic",
    category: "Digestive Spice",
    energetics: {
      temperature: "warm",
      taste: ["pungent", "sweet"],
      dosha: "vata",
    },
    benefits: [
      "Kindles digestive fire",
      "Reduces bloating",
      "Relieves nausea",
      "Improves circulation",
      "Warming and stimulating",
      "Anti-inflammatory",
    ],
    symptoms: [
      "poor digestion",
      "bloating",
      "nausea",
      "cold hands and feet",
      "poor circulation",
      "arthritis",
      "weak appetite",
    ],
    activeCompounds: ["gingerols", "shogaols", "zingiberene"],
    dosage: {
      tea: "1-2g fresh sliced daily",
      decoction: "2-4g for 10-15 minutes",
      powder: "1-2g twice daily",
      tincture: "10-20 drops 2-3 times daily",
    },
    contraindications: ["high pitta", "bleeding disorders", "ulcers"],
    interactions: ["May increase bleeding with anticoagulants"],
    sideEffects: ["heartburn in Pitta types", "may warm excessively"],
    researchStudies: [
      { title: "Ginger for Nausea and Digestion", year: 2020 },
      { title: "Zingiber officinale for Inflammation", year: 2021 },
      { title: "Ginger and Circulation", year: 2019 },
    ],
    season: "winter",
    traditionalUse: "Deepan (appetizer), stimulates agni",
    preparation: "Fresh slices in hot water or used in cooking",
    storageInstructions: "Store in cool place, wrapped in cloth",
    priceRange: "$1-3 per ounce",
    availability: "common",
    scientificName: "Zingiber officinale Roscoe",
    partUsed: "Fresh rhizome",
  },
  {
    id: "ayurvedic-holy-basil-006",
    name: "Holy Basil (Tulsi)",
    sanskritName: "तुलसी (Tulsi)",
    system: "ayurvedic",
    category: "Adaptogenic Immune",
    energetics: {
      temperature: "warm",
      taste: ["pungent", "bitter", "sweet"],
      dosha: "kapha",
    },
    benefits: [
      "Enhances immunity",
      "Reduces fever",
      "Clears respiratory passages",
      "Relieves stress",
      "Supports digestion",
      "Promotes circulation",
    ],
    symptoms: [
      "weak immunity",
      "fever",
      "cough",
      "stress",
      "poor digestion",
      "sluggish circulation",
      "brain fog",
    ],
    activeCompounds: ["eugenol", "carvacrol", "rosmarinic acid"],
    dosage: {
      tea: "2-5g fresh or dried daily",
      decoction: "3-6g for 10 minutes",
      powder: "1-2g twice daily",
      tincture: "10-20 drops 2-3 times daily",
    },
    contraindications: ["high pitta with heat", "pregnancy"],
    interactions: ["May interact with anticoagulants"],
    sideEffects: ["rare", "generally well-tolerated"],
    researchStudies: [
      { title: "Tulsi for Stress and Immunity", year: 2021 },
      { title: "Holy Basil for Respiratory Health", year: 2020 },
      { title: "Tulsi and Antioxidant Properties", year: 2019 },
    ],
    season: "year-round",
    traditionalUse: "Sattvic herb, protects and uplifts",
    preparation: "Fresh or dried leaves as tea",
    storageInstructions: "Store in sealed container away from light",
    priceRange: "$5-12 per ounce",
    availability: "common",
    scientificName: "Ocimum sanctum L.",
    partUsed: "Leaf",
  },
  {
    id: "ayurvedic-shatavari-007",
    name: "Shatavari",
    sanskritName: "शतावरी (Shatavari)",
    system: "ayurvedic",
    category: "Female Tonic",
    energetics: {
      temperature: "cool",
      taste: ["sweet", "bitter"],
      dosha: "vata",
    },
    benefits: [
      "Supports female reproductive health",
      "Nourishes all tissues",
      "Promotes lactation",
      "Soothes inflammation",
      "Supports hormonal balance",
      "Builds ojas (vitality)",
    ],
    symptoms: [
      "irregular periods",
      "low libido",
      "weak lactation",
      "pelvic inflammation",
      "hormonal imbalance",
      "menopausal symptoms",
      "infertility",
    ],
    activeCompounds: [
      "saponins",
      "asparagine",
      "polysaccharides",
      "arginine",
    ],
    dosage: {
      tea: "3-6g daily",
      decoction: "5-10g for 20 minutes",
      powder: "1-2g twice daily with warm milk",
      tincture: "20-30 drops 2-3 times daily",
    },
    contraindications: ["kapha excess", "ama (toxins)", "edema"],
    interactions: ["Generally no significant interactions"],
    sideEffects: ["may slow digestion in weak digestion", "generally well-tolerated"],
    researchStudies: [
      { title: "Shatavari for Female Reproductive Health", year: 2020 },
      { title: "Asparagus racemosus for Lactation", year: 2019 },
      { title: "Shatavari and Hormonal Balance", year: 2021 },
    ],
    season: "year-round",
    traditionalUse: "Female rasayana, supports all doshas",
    preparation: "Decoct or take as powder with warm milk",
    storageInstructions: "Store in sealed container",
    priceRange: "$10-20 per ounce",
    availability: "moderate",
    scientificName: "Asparagus racemosus Willd.",
    partUsed: "Root",
  },
  {
    id: "ayurvedic-guggul-008",
    name: "Guggul",
    sanskritName: "गुग्गुल (Guggul)",
    system: "ayurvedic",
    category: "Joint & Detoxification",
    energetics: {
      temperature: "warm",
      taste: ["pungent", "bitter"],
      dosha: "vata",
    },
    benefits: [
      "Reduces joint pain",
      "Supports joint mobility",
      "Detoxifies tissues",
      "Reduces cholesterol",
      "Supports circulation",
      "Reduces inflammation",
    ],
    symptoms: [
      "arthritis",
      "joint stiffness",
      "poor circulation",
      "high cholesterol",
      "inflammation",
      "toxic accumulation",
      "muscle pain",
    ],
    activeCompounds: [
      "guggulsterones",
      "sterols",
      "esters",
      "polysaccharides",
    ],
    dosage: {
      tea: "2-4g daily",
      decoction: "3-5g for 20 minutes",
      powder: "1-2g twice daily",
      tincture: "10-20 drops 2-3 times daily",
    },
    contraindications: [
      "pregnancy",
      "high pitta",
      "bleeding disorders",
      "ulcers",
    ],
    interactions: ["May interact with thyroid medications", "May reduce drug absorption"],
    sideEffects: ["acne in some", "upset stomach", "allergic reaction in rare cases"],
    researchStudies: [
      { title: "Guggul for Joint Health", year: 2020 },
      { title: "Guggulsterones and Cholesterol", year: 2021 },
      { title: "Guggul for Inflammation and Pain", year: 2019 },
    ],
    season: "winter",
    traditionalUse: "Removes ama, supports joints and circulation",
    preparation: "Decoct or take as powder, often in formulas",
    storageInstructions: "Store in cool, dry place",
    priceRange: "$12-25 per ounce",
    availability: "moderate",
    scientificName: "Commiphora wightii (Arn.) Bhandari",
    partUsed: "Resin",
  },
  {
    id: "ayurvedic-neem-009",
    name: "Neem",
    sanskritName: "नीम (Neem)",
    system: "ayurvedic",
    category: "Blood Purifier",
    energetics: {
      temperature: "cool",
      taste: ["bitter", "pungent"],
      dosha: "pitta",
    },
    benefits: [
      "Purifies blood",
      "Supports skin health",
      "Destroys parasites",
      "Reduces fever",
      "Anti-bacterial",
      "Removes toxins",
    ],
    symptoms: [
      "skin conditions",
      "acne",
      "parasitic infection",
      "fever",
      "blood toxicity",
      "poor skin",
      "infections",
    ],
    activeCompounds: ["azadirachtin", "nimbin", "salannin", "volatile oils"],
    dosage: {
      tea: "1-3g daily",
      decoction: "2-4g for 15 minutes",
      powder: "0.5-1g twice daily",
      tincture: "5-15 drops 2-3 times daily",
    },
    contraindications: ["blood deficiency", "vata excess", "pregnancy"],
    interactions: ["May increase liver metabolism of drugs"],
    sideEffects: [
      "bitter taste",
      "nausea in sensitive individuals",
      "diarrhea",
    ],
    researchStudies: [
      { title: "Neem for Skin Health", year: 2021 },
      { title: "Azadirachta indica as Blood Purifier", year: 2020 },
      { title: "Neem for Parasitic Infections", year: 2019 },
    ],
    season: "summer",
    traditionalUse: "Rakta shodhak, purifies blood",
    preparation: "Decoct or make into paste, or take as powder",
    storageInstructions: "Store in cool, dry place",
    priceRange: "$4-10 per ounce",
    availability: "common",
    scientificName: "Azadirachta indica A. Juss.",
    partUsed: "Leaf, bark, seed",
  },
  {
    id: "ayurvedic-amalaki-010",
    name: "Amalaki (Indian Gooseberry)",
    sanskritName: "आमलकी (Amalaki)",
    system: "ayurvedic",
    category: "Vitamin C Rich",
    energetics: {
      temperature: "cool",
      taste: ["sour", "sweet", "astringent"],
      dosha: "pitta",
    },
    benefits: [
      "Rich in vitamin C",
      "Supports immune function",
      "Anti-aging properties",
      "Improves digestion",
      "Supports bone health",
      "Promotes hair health",
    ],
    symptoms: [
      "weak immunity",
      "poor digestion",
      "weak bones",
      "hair loss",
      "premature aging",
      "constipation",
      "acidity",
    ],
    activeCompounds: [
      "ascorbic acid",
      "tannins",
      "polyphenols",
      "gallic acid",
    ],
    dosage: {
      tea: "2-5g daily",
      decoction: "3-6g for 15 minutes",
      powder: "1-2g twice daily",
      tincture: "10-20 drops 2-3 times daily",
    },
    contraindications: ["high pitta with heat", "loose stools"],
    interactions: ["Generally no significant interactions"],
    sideEffects: ["rare", "may cause loose stools in some"],
    researchStudies: [
      { title: "Amalaki for Antioxidant Support", year: 2021 },
      { title: "Phyllanthus emblica for Immune Function", year: 2020 },
      { title: "Amalaki and Hair Health", year: 2019 },
    ],
    season: "summer",
    traditionalUse: "Rasayana herb, supports all tissues",
    preparation: "Dried fruit powder in warm water, or fresh juice",
    storageInstructions: "Store in sealed container away from moisture",
    priceRange: "$5-12 per ounce",
    availability: "common",
    scientificName: "Phyllanthus emblica L.",
    partUsed: "Fruit",
  },
  {
    id: "ayurvedic-basti-001",
    name: "Sesame Oil (Til Tail)",
    sanskritName: "तिल तैल (Til Tail)",
    system: "ayurvedic",
    category: "Warming Oil",
    energetics: {
      temperature: "warm",
      taste: ["sweet"],
      dosha: "vata",
    },
    benefits: [
      "Warming and grounding",
      "Nourishes tissues",
      "Supports joint health",
      "Calms nervous system",
      "Improves skin",
      "Detoxifying",
    ],
    symptoms: [
      "vata imbalance",
      "joint pain",
      "dry skin",
      "anxiety",
      "insomnia",
      "poor circulation",
      "muscle tension",
    ],
    activeCompounds: ["sesamin", "vitamin E", "lignans"],
    dosage: {
      massage: "External application daily",
      internal: "1-2 teaspoons daily",
    },
    contraindications: ["kapha excess", "high pitta"],
    interactions: ["Generally no significant interactions"],
    sideEffects: ["may increase kapha in excess"],
    researchStudies: [
      { title: "Sesame Oil for Skin Health", year: 2020 },
      { title: "Sesamin and Joint Health", year: 2021 },
    ],
    season: "winter",
    traditionalUse: "Massage oil, nourishing and warming",
    preparation: "Used for abhyanga (oil massage)",
    storageInstructions: "Store in cool, dark place",
    priceRange: "$3-8 per ounce",
    availability: "common",
    scientificName: "Sesamum indicum L.",
    partUsed: "Seed oil",
  },
  {
    id: "ayurvedic-bacopa-011",
    name: "Bacopa (Water Hyssop)",
    sanskritName: "बाकोपा (Bacopa)",
    system: "ayurvedic",
    category: "Brain Tonic",
    energetics: {
      temperature: "cool",
      taste: ["bitter", "sweet"],
      dosha: "pitta",
    },
    benefits: [
      "Enhances memory",
      "Improves concentration",
      "Calms mind",
      "Supports nervous system",
      "Anti-inflammatory",
      "Reduces epilepsy symptoms",
    ],
    symptoms: [
      "poor memory",
      "lack of concentration",
      "mental fatigue",
      "epilepsy",
      "ADHD",
      "anxiety",
      "stress",
    ],
    activeCompounds: ["bacoside A", "bacoside B", "alkaloids"],
    dosage: {
      tea: "2-4g daily",
      decoction: "3-5g for 15 minutes",
      powder: "1-2g twice daily",
      tincture: "10-20 drops 2-3 times daily",
    },
    contraindications: ["vata excess", "cold conditions"],
    interactions: ["May increase sedation"],
    sideEffects: ["mild stomach upset", "nausea in some"],
    researchStudies: [
      { title: "Bacopa for Memory and Cognition", year: 2021 },
      { title: "Bacopa monnieri for Anxiety", year: 2020 },
      { title: "Bacopa and Neuroplasticity", year: 2019 },
    ],
    season: "summer",
    traditionalUse: "Medhya rasayana, promotes learning",
    preparation: "Decoct or consume as powder with warm water",
    storageInstructions: "Store in sealed container",
    priceRange: "$8-15 per ounce",
    availability: "moderate",
    scientificName: "Bacopa monniera (L.) Wettst.",
    partUsed: "Whole plant",
  },
  {
    id: "ayurvedic-dashmool-012",
    name: "Dashmool Tea",
    sanskritName: "दशमूल (Dashmool)",
    system: "ayurvedic",
    category: "Joint & Inflammation",
    energetics: {
      temperature: "warm",
      taste: ["bitter", "pungent"],
      dosha: "vata",
    },
    benefits: [
      "Supports joint health",
      "Reduces inflammation",
      "Warms the body",
      "Improves circulation",
      "Supports recovery",
      "Anti-spasmodic",
    ],
    symptoms: [
      "arthritis",
      "joint pain",
      "inflammation",
      "muscle pain",
      "spasms",
      "poor recovery",
      "cold constitution",
    ],
    activeCompounds: [
      "saponins",
      "alkaloids",
      "tannins",
      "polysaccharides",
    ],
    dosage: {
      tea: "2-4g daily",
      decoction: "3-6g for 20 minutes",
      powder: "1-2g twice daily",
      tincture: "15-25 drops 2-3 times daily",
    },
    contraindications: ["high pitta", "diarrhea"],
    interactions: ["Generally no significant interactions"],
    sideEffects: ["rare", "may cause warming effect"],
    researchStudies: [
      { title: "Dashmool for Inflammatory Conditions", year: 2020 },
      { title: "Dashmool and Joint Support", year: 2021 },
    ],
    season: "winter",
    traditionalUse: "Vatashamak, balances vata dosha",
    preparation: "Decoct 20 minutes, traditionally warming formula",
    storageInstructions: "Store in sealed container",
    priceRange: "$6-12 per ounce",
    availability: "moderate",
    scientificName: "Combination of 10 roots - Bilva, Shyonaka, Gambhari, Patala, Bhumyamalaki, Gokshura, Solanum, Tribulus, Vidarikand, Shalaparni",
    partUsed: "Roots",
  },
  {
    id: "ayurvedic-triphala-yoga-013",
    name: "Trikatu",
    sanskritName: "त्रिकटु (Trikatu)",
    system: "ayurvedic",
    category: "Digestive Stimulant",
    energetics: {
      temperature: "hot",
      taste: ["pungent"],
      dosha: "kapha",
    },
    benefits: [
      "Kindles digestive fire",
      "Removes ama (toxins)",
      "Improves metabolism",
      "Reduces kapha",
      "Stimulates appetite",
      "Anti-parasitic",
    ],
    symptoms: [
      "slow digestion",
      "kapha accumulation",
      "poor appetite",
      "weak metabolism",
      "obesity",
      "sluggishness",
      "parasitic infection",
    ],
    activeCompounds: [
      "piperine",
      "gingerols",
      "shogaols",
      "volatile oils",
    ],
    dosage: {
      tea: "0.5-1g daily",
      decoction: "1-2g for 10 minutes",
      powder: "0.5g twice daily",
      tincture: "5-10 drops 2-3 times daily",
    },
    contraindications: [
      "high pitta",
      "ulcers",
      "sensitive stomach",
      "pregnancy",
    ],
    interactions: ["May increase absorption of some drugs"],
    sideEffects: ["heartburn in Pitta types", "stomach irritation"],
    researchStudies: [
      { title: "Trikatu for Digestive Enhancement", year: 2020 },
      { title: "Piperine and Bioavailability", year: 2021 },
    ],
    season: "winter",
    traditionalUse: "Deepana, kindles agni (digestive fire)",
    preparation: "Take with warm water or add to food",
    storageInstructions: "Store in sealed container",
    priceRange: "$5-12 per ounce",
    availability: "common",
    scientificName: "Combination of Black Pepper, Long Pepper, Ginger",
    partUsed: "Rhizomes and fruits",
  },
  {
    id: "ayurvedic-brahmi-ghee-014",
    name: "Brahmi Ghee",
    sanskritName: "ब्राह्मी घी (Brahmi Ghee)",
    system: "ayurvedic",
    category: "Brain Nourishment",
    energetics: {
      temperature: "cool",
      taste: ["ghee-butter"],
      dosha: "pitta",
    },
    benefits: [
      "Deeply nourishes brain",
      "Enhances memory",
      "Supports meditation",
      "Calms mind",
      "Improves sleep quality",
      "Promotes sattvic state",
    ],
    symptoms: [
      "poor memory",
      "mental fatigue",
      "anxiety",
      "insomnia",
      "racing thoughts",
      "poor focus",
      "emotional imbalance",
    ],
    activeCompounds: [
      "bacosides",
      "ghee oils",
      "fat-soluble vitamins",
    ],
    dosage: {
      oral: "1-2 teaspoons daily",
      nasal: "2-3 drops in each nostril",
    },
    contraindications: ["high kapha", "obesity", "high cholesterol"],
    interactions: ["Generally no significant interactions"],
    sideEffects: ["may increase kapha in excess"],
    researchStudies: [
      { title: "Brahmi and Cognitive Enhancement", year: 2020 },
      { title: "Ghee for Brain Health", year: 2021 },
    ],
    season: "year-round",
    traditionalUse: "Medhya rasayana, elevates consciousness",
    preparation: "Traditional medicated ghee formulation",
    storageInstructions: "Store in cool place, sealed container",
    priceRange: "$15-30 per ounce",
    availability: "moderate",
    scientificName: "Bacopa monniera (L.) Wettst. infused in Ghee",
    partUsed: "Herb infused in ghee",
  },
  {
    id: "ayurvedic-aloe-vera-015",
    name: "Aloe Vera",
    sanskritName: "घृतकुमारी (Ghritakumari)",
    system: "ayurvedic",
    category: "Cooling & Detox",
    energetics: {
      temperature: "cool",
      taste: ["bitter"],
      dosha: "pitta",
    },
    benefits: [
      "Cools internal heat",
      "Supports digestion",
      "Liver detoxification",
      "Heals gut lining",
      "Anti-inflammatory",
      "Skin healing",
    ],
    symptoms: [
      "high pitta",
      "hyperacidity",
      "inflammation",
      "poor digestion",
      "skin conditions",
      "liver congestion",
      "constipation",
    ],
    activeCompounds: [
      "aloin",
      "emodin",
      "polysaccharides",
      "anthraquinones",
    ],
    dosage: {
      juice: "1-2 ounces daily",
      powder: "1-2g daily",
      gel: "1-2 tablespoons daily",
    },
    contraindications: ["pregnancy", "severe diarrhea", "dehydration"],
    interactions: ["May reduce absorption of medications"],
    sideEffects: [
      "laxative effect",
      "cramping",
      "electrolyte imbalance in high doses",
    ],
    researchStudies: [
      { title: "Aloe Vera for Digestive Health", year: 2020 },
      { title: "Aloe and Skin Healing", year: 2021 },
      { title: "Aloe Vera for Inflammatory Conditions", year: 2019 },
    ],
    season: "summer",
    traditionalUse: "Cools pitta, supports digestion and healing",
    preparation: "Fresh gel, juice, or powdered extract",
    storageInstructions: "Store fresh leaves in cool place",
    priceRange: "$2-6 per ounce",
    availability: "common",
    scientificName: "Aloe barbadensis Mill.",
    partUsed: "Leaf gel",
  },
  {
    id: "ayurvedic-licorice-016",
    name: "Licorice Root",
    sanskritName: "यष्टिमधु (Yashtimadhu)",
    system: "ayurvedic",
    category: "Sweet Rejuvenative",
    energetics: {
      temperature: "cool",
      taste: ["sweet"],
      dosha: "vata",
    },
    benefits: [
      "Soothes respiratory tract",
      "Supports adrenal function",
      "Anti-inflammatory",
      "Supports digestion",
      "Improves voice",
      "Detoxifying",
    ],
    symptoms: [
      "sore throat",
      "cough",
      "weak digestion",
      "stress",
      "adrenal fatigue",
      "inflammation",
      "hoarseness",
    ],
    activeCompounds: ["glycyrrhizin", "flavonoids", "saponins"],
    dosage: {
      tea: "1-3g daily",
      decoction: "2-4g for 15 minutes",
      powder: "0.5-1g twice daily",
      tincture: "5-10 drops 2-3 times daily",
    },
    contraindications: [
      "high blood pressure",
      "edema",
      "hypokalemia",
      "pregnancy",
    ],
    interactions: ["May interact with diuretics", "May interact with corticosteroids"],
    sideEffects: [
      "water retention in high doses",
      "high blood pressure",
      "hypokalemia",
    ],
    researchStudies: [
      { title: "Licorice for Respiratory Health", year: 2020 },
      { title: "Glycyrrhiza for Adrenal Support", year: 2021 },
      { title: "Licorice and Anti-inflammatory Properties", year: 2019 },
    ],
    season: "year-round",
    traditionalUse: "Rasayana, supports all tissues",
    preparation: "Decoct or make into tea",
    storageInstructions: "Store in cool, dry place",
    priceRange: "$2-6 per ounce",
    availability: "common",
    scientificName: "Glycyrrhiza glabra L.",
    partUsed: "Root",
  },
]

export function getHerbById(id: string): HerbalRemedyDetailed | undefined {
  const allHerbs = [...koreanHerbs, ...ayurvedicHerbs]
  return allHerbs.find((herb) => herb.id === id)
}

export function searchHerbs(query: string): HerbalRemedyDetailed[] {
  const allHerbs = [...koreanHerbs, ...ayurvedicHerbs]
  const lowerQuery = query.toLowerCase()
  return allHerbs.filter(
    (herb) =>
      herb.name.toLowerCase().includes(lowerQuery) ||
      herb.symptoms.some((s) => s.toLowerCase().includes(lowerQuery)) ||
      herb.benefits.some((b) => b.toLowerCase().includes(lowerQuery)) ||
      herb.category.toLowerCase().includes(lowerQuery) ||
      herb.scientificName.toLowerCase().includes(lowerQuery)
  )
}

export function getHerbsBySymptom(symptom: string): HerbalRemedyDetailed[] {
  const allHerbs = [...koreanHerbs, ...ayurvedicHerbs]
  const lowerSymptom = symptom.toLowerCase()
  return allHerbs.filter((herb) =>
    herb.symptoms.some((s) => s.toLowerCase().includes(lowerSymptom))
  )
}

export function getHerbsBySystem(system: "korean" | "ayurvedic" | "both"): HerbalRemedyDetailed[] {
  const allHerbs = [...koreanHerbs, ...ayurvedicHerbs]
  if (system === "both") return allHerbs
  return allHerbs.filter((herb) => herb.system === system || herb.system === "both")
}

export function getHerbsByDosha(dosha: "vata" | "pitta" | "kapha"): HerbalRemedyDetailed[] {
  return ayurvedicHerbs.filter((herb) => herb.energetics.dosha === dosha)
}
